-- Create dimension
-- CREATE TABLE DIM_EMPLOYEES (
--     EMPLOYEE_KEY INT IDENTITY(1,1) CONSTRAINT PK_EMPLOYEES PRIMARY KEY,
--     EMPLOYEE_ID NVARCHAR(10),
--     FULL_NAME NVARCHAR(80),
--     TITLE NVARCHAR(100),
--     -- HIRE_DATE DATE,
--     -- OFFICE_CODE NVARCHAR(20),
--     CITY NVARCHAR(60),
--     REGION NVARCHAR(60),
--     COUNTRY NVARCHAR(60),
--     REPORTS_TO INT,
-- 	DB_ORIGIN NVARCHAR(60)
-- );


-- Create view to add data in the dimension "dim_employees"

CREATE OR ALTER VIEW VDIM_EMPLOYEES AS
SELECT 
	[EMPLOYEE_ID],
	[FULL_NAME],
	[TITLE],
	[CITY],
	[COUNTRY],
	[REPORTS_TO],
	[DB_ORIGIN]
FROM (
	SELECT 
		CAST(EM.CODIGO_EMPLEADO AS NVARCHAR(10)) AS EMPLOYEE_ID, 
		EM.NOMBRE + ' ' + EM.APELLIDO1 AS FULL_NAME, 
		EM.PUESTO AS TITLE, 
		O.CIUDAD AS CITY,
		O.PAIS AS COUNTRY, 
		ISNULL(J.NOMBRE + ' ' + J.APELLIDO1, 'COMITE GERENCIAL') AS REPORTS_TO,
		'JARDINERIA' AS DB_ORIGIN
	FROM EMPLEADO EM
	LEFT JOIN OFICINA O ON EM.CODIGO_OFICINA = O.CODIGO_OFICINA
	LEFT JOIN EMPLEADO J ON EM.CODIGO_JEFE = J.CODIGO_EMPLEADO
	
	UNION
	
	SELECT 
		E.EMPLOYEEID AS EMPLOYEE_ID, 
		E.FIRSTNAME + ' ' + E.LASTNAME AS FULL_NAME, 
		E.TITLE AS TITLE, 
		E.CITY AS CITY,
		E.COUNTRY AS COUNTRY,  
		ISNULL(B.FIRSTNAME + ' ' + B.LASTNAME, 'COMITE GERENCIAL') AS REPORTS_TO,
		'NORTHWIND' AS DB_ORIGIN
	FROM EMPLOYEES E
	LEFT JOIN EMPLOYEES B ON E.REPORTSTO = B.EMPLOYEEID
) AS EMPLOYEES_DATA;

SELECT * FROM VDIM_EMPLOYEES;