-- Active: 1726878131637@@127.0.0.1@1433@staging
CREATE OR ALTER VIEW FACT_SALES AS
SELECT [Venta_KEY]
,[PRODUCT_KEY]
,[CUSTOMER_KEY]
,[EMPLOYEE_ID]
,[DATE_KEY]
,[QUANTITY]
,[UNIT_PRICE]
,[DISCOUNT]
,[DB_ORIGIN]
FROM (
SELECT
    O.OrderID AS Venta_KEY,
    CAST(OD.ProductID AS varchar(10)) AS PRODUCT_KEY,
    O.CustomerID AS CUSTOMER_KEY,
    O.EmployeeID AS EMPLOYEE_ID,
    CAST(O.ShippedDate AS DATE) AS DATE_KEY,
    OD.Quantity AS QUANTITY,
    OD.UnitPrice AS UNIT_PRICE,
    OD.Discount AS DISCOUNT,
    'NORTHWIND' AS DB_ORIGIN
FROM
    dbo.[ORDER DETAILS] AS OD
JOIN
    dbo.Orders AS O ON OD.OrderID = O.OrderID
WHERE O.ShippedDate IS NOT NULL
UNION
SELECT
    J.CODIGO_PEDIDO AS Venta_KEY,
    DP.CODIGO_PRODUCTO AS PRODUCT_KEY,
    CAST(J.CODIGO_CLIENTE AS varchar(10)) AS CUSTOMER_KEY,
    C.CODIGO_EMPLEADO_REP_VENTAS AS EMPLOYEE_ID,
    CAST(J.FECHA_ENTREGA AS DATE) AS DATE_KEY,
    DP.Cantidad AS QUANTITY,
    DP.PRECIO_UNIDAD AS UNIT_PRICE,
    0 AS DISCOUNT,
    'JARDINERIA' AS DB_ORIGIN
FROM
    dbo.DETALLE_PEDIDO AS DP
JOIN
    dbo.Pedido AS J ON DP.CODIGO_PEDIDO = J.CODIGO_PEDIDO
JOIN dbo.CLIENTE AS C ON J.CODIGO_CLIENTE = C.CODIGO_CLIENTE
WHERE J.FECHA_ENTREGA IS NOT NULL
) AS V;

SELECT * FROM FACT_SALES;

CREATE OR ALTER VIEW FactPagos AS
SELECT
    -- P.PagoID AS PagoID,
    P.CODIGO_CLIENTE AS ClienteID,
    CAST(P.FECHA_PAGO AS DATE) AS FechaID,
    P.TOTAL AS TotalPago,
    P.FORMA_PAGO AS FormaPago
FROM
    dbo.Pago AS P;

SELECT * FROM FactPagos;


